created Question model
TCP-Tech/mentorship-backend pull request #31
Opened 2022-11-06 13:01 UTC by animesh288

### Fixes #19 

### Description
Created Question model under questions app and generated migrations for the app.

**Type of Change:** 
- Code

**Code/Quality Assurance Only** 

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2022-11-07 16:44 UTC, sahil9001 requested changes

2022-11-07 16:44 UTC, sahil9001 commented on questions/models.py
> +    id=models.IntegerField(primary_key=True)
Not required, `Model` already has an `id` field.

2022-11-07 16:44 UTC, sahil9001 commented on questions/models.py
> +    topic=models.CharField(max_length=200)
`ForeignKey` field with `Topic` model.
Dependency : Topic Model

2022-11-07 16:44 UTC, sahil9001 commented on questions/models.py
> +    hackerrankLink=models.CharField(max_length=200)
Make this `URLField`

2022-11-07 16:44 UTC, sahil9001 commented on questions/models.py
> +    global_check=models.BooleanField(default=False)
Can you explain what's this for? Seems irrelevant.

2022-11-07 16:44 UTC, sahil9001 commented on questions/models.py
> +    level=models.CharField(max_length=20)
Make it `ChoiceField` with difficulty as 'easy' , 'medium' and 'hard'.

2022-11-07 16:44 UTC, sahil9001 commented on questions/models.py
> +    mentor_id=models.IntegerField()
Will be a `ForeignKey` when `Mentor` model is completed.

2022-11-08 05:37 UTC, animesh288 commented on questions/models.py
> +    global_check=models.BooleanField(default=False)
I added it following [this](https://drive.google.com/file/d/1rjZe-7mgDX1MGz6FY9YgBMY7_IpSH26-/view) schema.
Updated in the latest commit.

2022-11-08 05:38 UTC, animesh288 commented on questions/models.py
> +    mentor_id=models.IntegerField()
Commented out this field. Will update once the Mentor model is completed

2022-11-26 19:29 UTC, prakhar-asaiya commented
add a __str__ class as well @animesh288 .

2022-11-26 19:29 UTC, prakhar-asaiya commented
add a '__str__' method as well @animesh288.

2022-11-26 19:30 UTC, prakhar-asaiya commented
add a __'__str__'__ class as well @animesh288.

2022-12-14 16:23 UTC, ayushgoswamiabr commented
Seems Ok to me @sahil9001 I think all the requested changes are done will you take a look and approve it

2022-12-14 16:50 UTC, sahil9001 approved these changes

2022-12-14 17:14 UTC, ayushgoswamiabr approved these changes

2022-12-18 12:05 UTC, merged